### ISSUE TITLE
Postgres: How to get value of dvkOther?

### ISSUE THREAD

**Issue by moigagoo** [xzfc/ndb.nim#16]
It's clear how to get values from `DbValue`s of kinds `dvkBool`, `dvkInt`, and other except for `dvkOther`, because `o` is not exported in `DbValue`: https://xzfc.github.io/ndb.nim/v0.19.8/postgres.html#DbValue

**Comment by xzfc** [comment]
I haven't remembered why I hid it. Probably to make sure clients won't rely on it, so they would not get broken when new kinds are added.

Maybe it's better to add more specific kinds to ndb?

**Comment by moigagoo** [comment]
> Probably to make sure clients won't rely on it

There are cases when they are unavoidable. For example, I'm querying `information_schema.columns` to check the tables are properly created in the Norm tests. Postgres returns values of type `sql_identifier` for column names, which I'm checking: https://www.postgresql.org/docs/12/infoschema-columns.html

Since those are not TEXT, they get returned as dvkOther, so I can't compare the returned row with a reference row.

To work around that, I'm converting the values to strings with $ and comparing seqs of strings instead of rows. It works, but it wasn't obvious why I can't just compare to ?"id".

> Maybe it's better to add more specific kinds to ndb?
It sounds like a good idea. I just worry that most PG data types will become str in Nim, so why even bother—it's not like you extracting any additional information.

Maybe, it'd be better to return the data type name in DbOther and let the user work with that? And maybe add a constructor for DbOther, so that I could do something like this: initDbValue(kind=dvkOther, pgType = "sql_identifier")?

**Comment by xzfc** [comment]
> Since those are not TEXT, they get returned as dvkOther, so I can't compare the returned row with a reference row.
>
> To work around that, I'm converting the values to strings with $ and comparing seqs of strings instead of rows. It works, but it wasn't obvious why I can't just compare to ?"id".

You may specify the desired type in SQL query, like this: `db.rows(sql"select column_name::text from information_schema.columns")`.

---

> I just worry that most PG data types will become str in Nim

Yeah, I'm too. Another concern is that PostgeSQL has a lot of types, even the user-defined ones.

> Maybe, it'd be better to return the data type name in DbOther and let the user work with that?

I mean, suppose `DbMacAddress` is added to ndb. If an old code assumes that `macaaddr` will be `DbOther`, then this code will break.

---

Another option is to allow the column type to be specified as a generic type argument.
Like how it is done for SQLite: https://github.com/xzfc/ndb.nim/blob/v0.19.8/tests/tsqlite.nim#L262

Or like this:

```nim
# old
iterator rows*(…): Row = …
for row in db.rows(db, …):
  …

# new
iterator rows*[T](…): T = …
for row in db.rows[:seq[DbValue]](db, …):
  # same semantics as in the old version
  …
for name, prec in db.rows[:(string, int64)](db, "SELECT column_name, numeric_precision from information_schema.columns"):
  # Let the user specify what types they expect.
  # Specifying `string` for every type is fine if you want the string representation.
  …
```

**Comment by moigagoo** [comment]
@xzfc the issue didn't end with a resolution last time, but the need to access `o` field would still be appreciated. This time, it's to support `VARCHAR` and `CHAR` types along with `TEXT`. Both are considered `dvkOther` and therefore can't deliver their values with `s`. Type casting would require query modification, which unnecessarily complicates the query generation logic.

So far, I can't see a better solution that to just let the user access `o.value`. At least, that would work for me.

I've submitted a tiny PR that exports `o` field: https://github.com/xzfc/ndb.nim/pull/17 There's basically zero code review required (it's literally just one symbol), but as the package owner and maintainer, you should make the decision to accept or reject it.
