### ISSUE TITLE
Fix statement finalization

### ISSUE THREAD

**Issue by nigredo-tori** [xzfc/ndb.nim#3]
Current implementation does not finalize statements in case of a mismatched argument list, or a runtime failure. As a result we get a `DbError` ("unable to close due to unfinalized statements or unfinished backups") when closing the database.

The reason for this is that the implementation mixes `return` statements with custom error handling (like [this](https://github.com/xzfc/ndb.nim/blob/489ee883b82273a10bce960eff98d25459c04d6b/ndb/sqlite.nim#L447-L459)).

See tests in #4 for failing examples.

**Comment by xzfc** [comment]
Thank you.
